### PR TITLE
Added favicon icon.

### PR DESCRIPTION
**Pull request by dovy**
#hacktoberfest

Here you go. Made a transparent PNG from the best quality version I could find, then a Favicon.

### CODE REVIEW

**Comment by dovy** [comment]
For issue #43

**Comment by Lablnet** [comment]
Replace icon file with original, sorry actually its logo not icon

**Comment by dovy** [comment]
I don’t understand what you are saying.

**Comment by Lablnet** [comment]
> I don’t understand what you are saying.

I mean the file "icon.png' should be same as before, we have to just change faviocn file which you did already

**Comment by dovy** [comment]
The png I provided has a transparent background and is cleaned up a little. I mean you could hand that to an designer and they should be able to recreate it. That’s why I put 2 files in the commit. Just letting you know.

**Pull request merged**
